services:
  forntend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - --nginx.scrape-uri=http://nginx:8080/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - forntend